### ISSUE TITLE
Issue with screeshot

### ISSUE THREAD

**Issue by bugith** [woheller69/Arity#1]
Android 12
Maybe related to permissions or some kind of FS inotify or inter-apps communications bus.
Maybe this is not an issue with Arity 1.29 as I didn't use the feature before : once captured a 2D function picture, the capture won't show in the gallery (Pictures/Screenshot) (latest Aves from D-Droid or native G-photo). Although, it shows in file explorer (Simple File Manager).
Once rebooted, the screenshot shows everywhere expected.
This is not a huge issue, as we can immediately find the capture in file explorer.

**Comment by woheller69** [comment]
Not sure if I understand correctly. For me it works well. The screenshot is saved in Pictures/screenshots.

After taking the screenshot simply open the gallery app and the image should be there.

 I removed the feature that the gallery is opened automatically. Maybe that is what you mean.

**Comment by bugith** [comment]
No Wol, I didn't even know the gallery opened automatically. Maybe this is only an issue in my own phone. Don't worry. Let's close and wait anybody reporting the same.
Although, what's strange is when I take a picture with the camera I don't need to reboot for it to show in the gallery. But it is not the same directory (DCIM vs Pictures/Screenshots). As I said this may be a permission setting or issue only in my phone. But something I can't figure is when I reboot then the captures done before reboot show in gallery, not the post-reboot ones ????
Don't worry and feel free to close.

**Comment by woheller69** [comment]
If the explorer finds it immediately but your gallery app does not then that is an issue of your gallery app. Maybe try a different gallery app.
The old version did not store in Pictures/screenshots it stored directly on /screenshots
But due to Google storage access framework bullshit this is no longer possible. Therefore I moved it to Pictures folders

**Comment by woheller69** [comment]
Have you tried the new higher resolution options (in settings) for 3d graphs?
The impressing 3d graphing capability led me to the decision that this app earns an extended life :-)

**Comment by bugith** [comment]
Wahoo, nicer than [this](https://androidforums.com/threads/arity-calculator-takes-graphing-to-a-new-level.98458/) isn't it?
