### ISSUE TITLE
android custom icon theming support

### ISSUE THREAD

**Issue by RustoMCSpit** [woheller69/Arity#13]

**Comment by woheller69** [comment]
Please try.

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/Arity/files/11998204/app-release.apk.zip)

**Comment by RustoMCSpit** [comment]
> Please try.
> 
> Uninstall Remove .zip and install
 
could you put it in the files section so f droid can see it

**Comment by RustoMCSpit** [comment]
> Please try.
> 
> Uninstall Remove .zip and install
> 
> [app-release.apk.zip](https://github.com/woheller69/Arity/files/11998204/app-release.apk.zip)

i cant open the .zip on my phone apparentlu, sorry

**Comment by RustoMCSpit** [comment]
> could you put it in the files section so f droid can see it

i mean obtainium not f droid, obyainium would auto pixk it up in the files

**Comment by woheller69** [comment]
> Remove .zip

...

**Comment by RustoMCSpit** [comment]
> > Remove .zip
> 
> ...

right figured it out, it works. problem is the loadinf screen still shows the low res non-monochrome version. also, could you put the .apk in the files, i currently have two versions of arity. i cant use the f droid store sorr
