### ISSUE TITLE
utilise the full top banner

### ISSUE THREAD

**Issue by RustoMCSpit** [woheller69/Arity#15]
arity only makes a strip grey and then has black above it. i think it should cover everythinf and remove tbe black top. also, i think grey should be the dominant color and black should be the top strip (secondary) but this could be an option. if it were to be an option allowing users to input hexs for preferred color would be ideal. thanks

**Comment by woheller69** [comment]
Next version will use Material 3 and dynamic colors according to selected theme. Status bar (small strip) and toolbar colors are handled automatically by theme

**Comment by RustoMCSpit** [comment]
> Next version will use Material 3 and dynamic colors according to selected theme. Status bar (small strip) and toolbar colors are handled automatically by theme

okay awesome, when that update comes round please put the .apk in the files thanks!
