### ISSUE TITLE
The some buttons are invisible

### ISSUE THREAD

**Issue by plum7x** [woheller69/Arity#21]
The some buttons are invisible, following screenshot.
This issue started in version 1.44.
In the old version 1.42, have no this issue.

![Screenshot_20230824-010300_1](https://github.com/woheller69/Arity/assets/106440424/cc7edad3-cbb8-4dc1-a45e-0de870dca32b)

System: Android 13
App version: 1.44, 1.46

**Comment by woheller69** [comment]
It seems you have a white theme. E.g. the frame around result is white. So white text on white background. Is dynamic colors switched on?
