### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by SirCrownguard** [woheller69/Arity#23]
[strings.txt](https://github.com/woheller69/Arity/files/12506236/strings.txt)

**Comment by woheller69** [comment]
There is also a help file

https://github.com/woheller69/Arity/blob/master/app/src/main/assets/help-en.html

**Comment by SirCrownguard** [comment]
I understand, I'm new to translating on GitHub and I'm just gaining experience. It seems I need to check if the applications have a help file.

**Comment by woheller69** [comment]
That is very app specific :-)

**Comment by woheller69** [comment]
Please try.

-Uninstall
-Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/Arity/files/12569998/app-release.apk.zip)

**Comment by SirCrownguard** [comment]
Hi,The version you sent me works and the translation is correct.I'm sorry to keep you waiting, but I guess I need to buy a new PSU now since my computer has a cable burn. I'm not sure if my motherboard is damaged or not.But I still apologize to you. Because I was the one who said I would translate for you, and now I've let you down. I hope you will forgive me. When I make my computer usable again, I will try to translate your projects into Turkish.Best Regards,Ertuğrul10 Eyl 2023 22:14 tarihinde woheller69 ***@***.***> yazdı:
Please try.
-Uninstall
-Remove .zip and install
app-release.apk.zip
