### ISSUE TITLE
New colour palette makes app almost unasable

### ISSUE THREAD

**Issue by emilfihlman** [woheller69/Arity#29]
Revert colour palette changes to original, as shown in the pictures. Current colour palette has the colours way too muted and close together.

**Comment by woheller69** [comment]
App uses dynamic colors which depend on your theme.

**Comment by woheller69** [comment]
Will add an option in settings to switch off dynamic colors

**Comment by emilfihlman** [comment]
I suspected this and tried switching between dark and light themes, force closing the app in between etc, but that didn't change the theme for me : /

Anycase an option to switch themes is great, thank you, and thank you for working on this!

**Comment by emilfihlman** [comment]
Accidentally clicked close

**Comment by woheller69** [comment]
It is not based on light or dark theme, but on the color range of your background image

**Comment by woheller69** [comment]
Please try. 

Uninstall
Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/Arity/files/12885269/app-release.apk.zip)

**Comment by emilfihlman** [comment]
The new version hit F-Droid and now the colours are still muted and close together, and very strangely orange, which has never been anything I have picked nor is it anywhere in my phone colours:

![Screenshot_20231029_113914](https://github.com/woheller69/Arity/assets/9070088/684ed853-4e1a-43ac-9f90-624e4e31e847)

Could you please restore the original colour palette as an option? Ie the one we see in all the screenshots where the first graph is white, next iirc was light blue, etc, or allow us to define how colours are picked by ourselves, perhaps by some formula.

Thank you!

**Comment by emilfihlman** [comment]
@woheller69 also I think it would be good to be able to reopen closed issues

**Comment by woheller69** [comment]
In the new version you have an option to switch off dynamic colors

**Comment by woheller69** [comment]
In the new version you have an option to switch off dynamic colors

**Comment by emilfihlman** [comment]
@woheller69 yes, I have the new version where there is a switch to switch off dynamic colors.

This is whay they look like

![Screenshot_20231029_120202](https://github.com/woheller69/Arity/assets/9070088/9f96ea30-0ebd-4b13-af3c-d4962c586aca)
![Screenshot_20231029_120207](https://github.com/woheller69/Arity/assets/9070088/ac571ff1-7893-4739-bb96-64d6c1c9d2ff)
![Screenshot_20231029_120216](https://github.com/woheller69/Arity/assets/9070088/e0ce7365-440e-42f5-9a3b-c1591d96257e)

Ie this switch doesn't restore the original colours.

**Comment by woheller69** [comment]
Maybe you need to restart to apply

**Comment by emilfihlman** [comment]
I have restarted the app, and the phone, and the screenshots show that I have switched the dynamic colors on and off, and the color theme changes from blue to orange in doing that.

**Comment by woheller69** [comment]
yes the color theme changes from your own theme to the default orange theme

**Comment by emilfihlman** [comment]
The default orange theme suffers from the same issues as the adaptive theme regarding visibility, and the default orange theme is pretty bad looking, and doesn't match what's shown in the screenshots shown for this.

Would you please consider allowing us either to set our own themes or adding a button to have a high contrast theme, preferably a similar one as shown in the screenshots.

**Comment by woheller69** [comment]
Next version will have an improved orange color scheme closer to the old orange scheme

You can try here:
Uninstall
Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/Arity/files/13198629/app-release.apk.zip)

**Comment by woheller69** [comment]
![Screenshot_20231029-180700](https://github.com/woheller69/Arity/assets/68678880/8eb10c3f-6d1a-4000-b9fb-4055115c6c4f)
