### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by supsm** [woheller69/Arity#30]
It would be nice if there were some haptic feedback on button press, otherwise it feels dull. Not sure how this is accomplished, but [florisboard](https://github.com/florisboard/florisboard) has it so it might be a good place to look.

**Comment by woheller69** [comment]
Please try. 

Uninstall
Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/Arity/files/12885269/app-release.apk.zip)

**Comment by supsm** [comment]
Sorry, how does this work? Extracting it produces a folder, and installing the zip directly says it's invalid.

**Comment by woheller69** [comment]
Only rename. Remove .zip
Do not extract

Am 13. Oktober 2023 17:40:13 MESZ schrieb supsm ***@***.***>:
>Sorry, how does this work? Extracting it produces a folder, and installing the zip directly says it's invalid.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/woheller69/Arity/issues/30#issuecomment-1761723263
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
--------------------------------------------
Dr. Wolfgang Heller
Tassilostr. 7
85551 Kirchheim
089 90490545
0157 52226269

**Comment by woheller69** [comment]
Only rename from apk.zip to .apk

**Comment by supsm** [comment]
Seems like there are a *lot* of vibrations. Each time I press a key it goes off a dozen times, then vibrares more when I move my finger. I expect it to vibrate a single time when I first press the button, and additionally each time a character is deleted when the delete key is held. I suppose there is haptic feedback... just not in a way that is desirable.

**Comment by woheller69** [comment]
It vibrates exactly once on each touch event.

But if that is not ok, I can remove that feature again. That is all I can do.

**Comment by woheller69** [comment]
Think I found it. I need to limit to touch down events and repeat

**Comment by woheller69** [comment]
Should work now
[app-release.apk.zip](https://github.com/woheller69/Arity/files/12902408/app-release.apk.zip)

**Comment by supsm** [comment]
Looks great, thanks a lot!
