### ISSUE TITLE
Letter keyboard not available in landscape mode

### ISSUE THREAD

**Issue by Macka323** [woheller69/Arity#33]
Letter keyboard not available in landscape mode.

And also can i make the kayboard always is open. Without having to click on the button to exapnd it every time i open the app.

![Screenshot_20231028_195327](https://github.com/woheller69/Arity/assets/75259519/a4b2641e-b8c3-4cf7-8199-e7f1c067baca)

![Screenshot_20231028_195415](https://github.com/woheller69/Arity/assets/75259519/cb82be76-d360-455d-84d5-ce464a8bb44a)

**Comment by woheller69** [comment]
yes, in landscape mode functionality is reduced.

The extended keyboard cannot be opened permanently at the moment

**Comment by woheller69** [comment]
maybe in future a long click on the button will lock it until closed manually

**Comment by Macka323** [comment]
> yes, in landscape mode functionality is reduced.
> 
> The extended keyboard cannot be opened permanently at the moment

Will there be a fix for this at the moment or?

**Comment by woheller69** [comment]
landscape mode will stay as it is.

locking the extended keyboard may be added in future
