### ISSUE TITLE
Keyboard spacing

### ISSUE THREAD

**Issue by ThatOneCalculator** [woheller69/Arity#34]
Right now, the keyboard is functional but extremely cramped. Adapting something similar to the official Google Calculator app might help with usability. 

Current:

![Screenshot_20231029-130529.png](https://github.com/woheller69/Arity/assets/44733677/f3de6bc6-4d04-422c-a624-416724aa1a26)

"Mockups" (aka, overlaying the Google Calculator keyboard)

![1698610151192.png](https://github.com/woheller69/Arity/assets/44733677/b49dfa04-8bd2-4010-821c-60ea53aeef72)

![1698610121064.png](https://github.com/woheller69/Arity/assets/44733677/ef4b8e4c-262e-45dc-b0f8-e7e243a9d8c4)

**Comment by Usland123** [comment]
There are no letters on the new keyboard, but i think the old one needs to be remade

**Comment by ThatOneCalculator** [comment]
Yeah. Maybe swiping on the symbols could reveal a text keyboard?

**Comment by Usland123** [comment]
i think there should be letters instead of functions, functions can be used by typing them in the input bar like now

**Comment by woheller69** [comment]
I will not make such big changes on the layout

**Comment by ThatOneCalculator** [comment]
Why? It's a great app functionality wise, but in terms of user experience it leaves a lot to be desired. On an average size phone (Pixel 7), the keys are too small to hit.
