### ISSUE TITLE
Please add/honor setting to disable haptic feedback

### ISSUE THREAD

**Issue by plpau** [woheller69/Arity#35]
Version 1.52 introduces haptic feedback and dynamic colors, however the device setting to disable haptic feedback is ignored by the app, and there seems to be no in-app user setting to disable haptic feedback, like there is for dynamic colors.

Ideally, please honor the device setting to enable or disable haptic feedback, or at least, please provide an in-app setting for people who find haptic feedback annoying.

Thanks for your time and attention.

**Comment by woheller69** [comment]
On my Android 13 device this works automatically...

Please try this version.
-Uninstall
-Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/Arity/files/13205636/app-release.apk.zip)

**Comment by plpau** [comment]
I have read there were API changes between Android 12 and 13 concerning the system setting for haptic feedback. I have tested version 1.52 on an Android 12 device and haptic feedback is enabled regardless of system setting. I have no way to check at this time, but if it is working on Android 13 it may be assumed that your current code is proper for the Android 13 way only.

If you cannot test on Android <= 12, I may find the time to try compiling and testing changes if you provide source patches, as opposed to apk files with undisclosed source.

Thanks for your time.

**Comment by woheller69** [comment]
can you try the above version on your device?

**Comment by woheller69** [comment]
it should also work on older Android versions

**Comment by plpau** [comment]
I am available to help with testing source patches, by compiling my own version, and not to install apk's provided without source. Thanks for your understanding.

I made some experiments by following documentation at https://developer.android.com/develop/ui/views/haptics/haptic-feedback?hl=en

The attached patch is quick-and-dirty and can be improved upon, but it seems to show that by using the View.performHapticFeedback method as recommended above, the system setting is properly taken into account, and there is no haptic feedback if disabled by the user. If that's what you're doing in your changes, I figure you can disregard this diff completely and build upon your code (also please note: the diff file was built against the source for 1.52 downloaded from f-droid.org).

OTOH some devices may not explicitly support haptic feedback (particularly older ones), in spite of supporting vibration. In these cases, following the recommendation to use the View method will likely result in no haptic feedback regardless of any system settings (at least that's what happened on devices where I could run tests). Your vibrate() function may be used to simulate haptic feedback in these cases, but: 1. I am unsure how to detect these cases, 2. adding an app setting to enable this behaviour may be the only way to give the user a choice.
