### ISSUE TITLE
[Feature request] Add switch to change between radians and degrees

### ISSUE THREAD

**Issue by Vitaspiros** [woheller69/Arity#39]
Hello everyone,
Currently the app supports only radians. It would be nice to have a button or a section in the Settings for changing between radians and degrees. You could add that option in the Settings or add a button writing 'RAD' or 'DEG', like the other calculator apps for easy accessibility.

**Comment by woheller69** [comment]
sind() etc are available

**Comment by Vitaspiros** [comment]
Oh, ok, I didn't know that!
Should I close this issue now or leave it open for further discussion?
