### ISSUE TITLE
[Feature request] Suport for displaying numeric results using a binary or hexadecimal representation.

### ISSUE THREAD

**Issue by LucasLehmann** [woheller69/Arity#40]
As someone who sometimes does math in conjunction with computing, not needing to convert from decimal to binary or hex would be convenient. Being able to represent numbers using octal would also be nice, though converting between that and decimal or hex is trivial.
Out of my interest in mathematical notation being able to specify how values are represented/possibly custom symbols and bases would be cool but not particularly useful outside being interesting, so that is probably not worth much effort.

I wouldn't mind doing this myself but I'm not particularly familiar java nor development for android
though I wouldn't mind trying if I had a short overview of what is relevant.

**Comment by woheller69** [comment]
I am only maintaining this app regarding new Android version updates, etc. Such a feature would be complex in my view and I do not know the code good enough either...

**Comment by woheller69** [comment]
of course that conversion is a simple task but it is not the way ArityEngine Interpreter works

https://github.com/woheller69/ArityEngine
