### ISSUE TITLE
[Feature Suggestion] Thousands separation

### ISSUE THREAD

**Issue by janilowski** [woheller69/Arity#41]
Hello,
I find your calculator very useful and use it almost every day at my university. I would like to suggest a feature that would improve readability of calculation results.
I think the result of an equation would be much more readable if it used thousands separators.

For example, instead of displaying a large number like this:
`4789237894`
The calculator could display it like this:
`4 789 237 894`
Or like this:
`4'789'237'894`

...making the result much more readable! Let me know what do you think about it. :smiley:

**Comment by woheller69** [comment]
This can be difficult. The result is not always a simple number, it can also be a complex number. And the result can be reused for further computation or for being copied. Such modifications would for sure cause problems.

**Comment by janilowski** [comment]
Okay. Well my idea only concerned the display of numeric results, especially large numbers. Perhaps the result of an equation could be held in memory, but displayed with thousands separators to the user?
This way, whenever copying or computing further, the results are unaffected.
