### ISSUE TITLE
Keyboard remember state

### ISSUE THREAD

**Issue by Naheel-Azawy** [woheller69/Arity#7]
First, I'd like to thank you for preserving this piece of software. I haven't seen a sane calculator app since cyanogenmod days.

The letters keyboard keeps disappearing in a frustrating way.
Example scenario: I open the app, press that arrow icon to show letters, type "x" (letters disappear), press the arrow icon again, type "+y" (letters disappear again), press the arrow icon again, and so on.
It seems that it disappears when the view changes.
I'd like it to always remember its last state. So if the letters were shown before I close the application and then reopen, it should keep them shown.

**Comment by woheller69** [comment]
will check. But that only happens with x and y when changing to 2d/3d graph.
