### ISSUE TITLE
SVG icons

### ISSUE THREAD

**Issue by Naheel-Azawy** [woheller69/Arity#8]
The delete, enter, and unfold arrow icons look a bit out of place.
Using SVG icons would be much nicer. Suggested icons:
- [backspace](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:backspace:FILL@0;wght@400;GRAD@0;opsz@48&icon.platform=web)
- [enter](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:keyboard_return:FILL@0;wght@400;GRAD@0;opsz@48)
- [unfold](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:unfold_more:FILL@0;wght@400;GRAD@0;opsz@48)

**Comment by woheller69** [comment]
good idea. Will try them

**Comment by woheller69** [comment]
Please try. Also with keyboard remember state.

Uninstall
Remove .zip
Install

[app-release.apk.zip](https://github.com/woheller69/Arity/files/11010365/app-release.apk.zip)

**Comment by Naheel-Azawy** [comment]
Looks great. Thanks.
